--Exercise 1--
CREATE TABLE STUDENTS (
    STUDENT_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(30),
    LAST_NAME VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(60) UNIQUE,
    ENROLL_DATE DATE NOT NULL,
    FEES NUMBER(8,2) DEFAULT 0
);

--Exercise 2--
CREATE TABLE DEPARTMENTS (
    DEPT_ID NUMBER PRIMARY KEY,
    DEPT_NAME VARCHAR2(50) UNIQUE NOT NULL,
    LOCATION VARCHAR2(50)
);

--Exercise 3--
ALTER TABLE STUDENTS
ADD DEPT_ID NUMBER REFERENCES DEPARTMENTS(DEPT_ID);

--Exercise 4--
ALTER TABLE STUDENTS ADD (
    PHONE VARCHAR2(20),
    STATUS VARCHAR2(10) DEFAULT 'ACTIVE'
);

--Exercise 5--
ALTER TABLE STUDENTS MODIFY PHONE VARCHAR2(30);

--Exercise 6--
ALTER TABLE STUDENTS DROP COLUMN STATUS;

--Exercise 7--
ALTER TABLE STUDENTS SET UNUSED (PHONE);

--Exercise 8--
ALTER TABLE STUDENTS DROP UNUSED COLUMNS;

--Exercise 9--
CREATE TABLE STUDENTS_ARCHIVE AS
SELECT * FROM STUDENTS WHERE 1=0;

--Exercise 10--
ALTER TABLE STUDENTS_ARCHIVE RENAME TO STUDENTS_OLD;

--Exercise 11--
ALTER TABLE STUDENTS
ADD CONSTRAINT chk_fees CHECK (FEES >= 0);

--Exercise 12--
ALTER TABLE STUDENTS
ADD CONSTRAINT uq_email UNIQUE (EMAIL) DEFERRABLE INITIALLY DEFERRED;

--Exercise 13--
ALTER TABLE STUDENTS DISABLE CONSTRAINT chk_fees;

--Exercise 14--
ALTER TABLE STUDENTS ENABLE CONSTRAINT chk_fees;

--Exercise 15--
ALTER TABLE STUDENTS DROP CONSTRAINT uq_email;

--Exercise 16--
INSERT INTO DEPARTMENTS VALUES (10, 'IT', 'Johannesburg');
INSERT INTO DEPARTMENTS VALUES (20, 'HR', 'Cape Town');
INSERT INTO DEPARTMENTS VALUES (30, 'Finance', 'Durban');

--Exercise 17--
INSERT INTO STUDENTS VALUES (1, 'John', 'Smith', 'john.smith@email.com', SYSDATE, 2000, 10);
INSERT INTO STUDENTS VALUES (2, 'Emily', 'Johnson', 'emily.johnson@email.com', SYSDATE, 1500, 20);
INSERT INTO STUDENTS VALUES (3, 'Michael', 'Brown', 'michael.brown@email.com', SYSDATE, 2500, 30);
INSERT INTO STUDENTS VALUES (4, 'Sophia', 'Williams', 'sophia.williams@email.com', SYSDATE, 1800, 10);
INSERT INTO STUDENTS VALUES (5, 'Daniel', 'Miller', 'daniel.miller@email.com', SYSDATE, 3000, 20);
INSERT INTO STUDENTS VALUES (6, 'Olivia', 'Davis', 'olivia.davis@email.com', SYSDATE, 2200, 30);
SELECT * FROM STUDENTS;

--Exercise 18--
UPDATE STUDENTS SET FEES = FEES * 1.10;

--Exercise 19--
DELETE FROM STUDENTS WHERE STATUS = 'INACTIVE';

--Exercise 20--
UPDATE STUDENTS
SET DEPT_ID = (SELECT DEPT_ID FROM DEPARTMENTS WHERE DEPT_NAME = 'COMPUTER SCIENCE')
WHERE DEPT_ID = (SELECT DEPT_ID FROM DEPARTMENTS WHERE DEPT_NAME = 'IT');

--Exercise 21--
SELECT S.FIRST_NAME || ' ' || S.LAST_NAME AS FULL_NAME,
       D.DEPT_NAME,
       S.ENROLL_DATE
FROM STUDENTS S
JOIN DEPARTMENTS D ON S.DEPT_ID = D.DEPT_ID;
DESC STUDENTS;
ALTER TABLE STUDENTS ADD ENROLL_DATE DATE;

--Exercise 22--
SELECT * FROM STUDENTS WHERE FEES > 1000;
ALTER TABLE STUDENTS ADD FEES NUMBER(8,2) DEFAULT 0;

--Exercise 23--
SELECT * FROM STUDENTS ORDER BY LAST_NAME ASC;

--Exercise 24--
SELECT S.FIRST_NAME, S.LAST_NAME, D.DEPT_NAME
FROM STUDENTS S
INNER JOIN DEPARTMENTS D ON S.DEPT_ID = D.DEPT_ID;

--Exercise 25--
SELECT D.DEPT_NAME, COUNT(*) AS NUM_STUDENTS
FROM STUDENTS S
JOIN DEPARTMENTS D ON S.DEPT_ID = D.DEPT_ID
GROUP BY D.DEPT_NAME;

--Exercise 26--
SELECT SUM(FEES) AS TOTAL_FEES,
       AVG(FEES) AS AVG_FEES,
       MAX(FEES) AS MAX_FEES,
       MIN(FEES) AS MIN_FEES
FROM STUDENTS;

--Exercise 27--
SELECT * FROM STUDENTS WHERE LAST_NAME LIKE 'M%';

--Exercise 28--
SELECT * FROM STUDENTS
WHERE ENROLL_DATE BETWEEN TO_DATE('2024-01-01','YYYY-MM-DD')
                      AND TO_DATE('2024-12-31','YYYY-MM-DD');
INSERT INTO STUDENTS VALUES (7, 'Liam', 'Taylor', 'liam.taylor@email.com',
    TO_DATE('2023-05-15','YYYY-MM-DD'), 2100, 10);

--Exercise 29--
SELECT * FROM STUDENTS WHERE DEPT_ID IN (10,20,30);

--Exercise 30--
SELECT DISTINCT D.DEPT_NAME
FROM STUDENTS S
JOIN DEPARTMENTS D ON S.DEPT_ID = D.DEPT_ID;

--Exercise 31--
SELECT * FROM STUDENTS
WHERE FEES > (SELECT AVG(FEES) FROM STUDENTS);

--Exercise 32--
SELECT * FROM DEPARTMENTS D
WHERE NOT EXISTS (SELECT 1 FROM STUDENTS S WHERE S.DEPT_ID = D.DEPT_ID);

--Exercise 33--
SELECT DEPT_NAME AS NAME FROM DEPARTMENTS
UNION
SELECT LAST_NAME FROM STUDENTS;

--Exercise 34--
SELECT FIRST_NAME, LAST_NAME,
       CASE
         WHEN FEES > 5000 THEN 'HIGH'
         WHEN FEES BETWEEN 2000 AND 5000 THEN 'MEDIUM'
         ELSE 'LOW'
       END AS FEE_LEVEL
FROM STUDENTS;

--Exercise 35--
SELECT D.DEPT_NAME, COUNT(*) AS NUM_STUDENTS
FROM STUDENTS S
JOIN DEPARTMENTS D ON S.DEPT_ID = D.DEPT_ID
GROUP BY D.DEPT_NAME
HAVING COUNT(*) > 3;

--Exercise 36--
CREATE SEQUENCE SEQ_STUDENTS START WITH 1000 INCREMENT BY 1;

--Exercise 37--
CREATE INDEX idx_lastname ON STUDENTS(LAST_NAME);

--Exercise 38--
CREATE VIEW VW_STUDENT_DETAILS AS
SELECT FIRST_NAME || ' ' || LAST_NAME AS FULL_NAME,
       D.DEPT_NAME,
       FEES
FROM STUDENTS S
JOIN DEPARTMENTS D ON S.DEPT_ID = D.DEPT_ID;

--Exercise 39--
SELECT * FROM (
    SELECT FIRST_NAME, LAST_NAME, FEES
    FROM STUDENTS
    ORDER BY FEES DESC
) WHERE ROWNUM <= 3;

--Exercise 40--
DROP VIEW VW_STUDENT_DETAILS;

















