

CREATE TABLE DEPARTMENTS (
    DEPT_ID NUMBER PRIMARY KEY,
    DEPT_NAME VARCHAR2(50) UNIQUE NOT NULL,
    LOCATION VARCHAR2(50)
);

CREATE TABLE STUDENTS (
    STUDENT_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(30),
    LAST_NAME VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(60),
    ENROLL_DATE DATE NOT NULL,
    FEES NUMBER(8,2) DEFAULT 0
);



ALTER TABLE STUDENTS
ADD CONSTRAINT UQ_EMAIL UNIQUE;

ALTER TABLE STUDENTS
ADD DEPT_ID NUMBER;

ALTER TABLE STUDENTS
ADD CONSTRAINT FK_DEPT
FOREIGN KEY (DEPT_ID)
REFERENCES DEPARTMENTS(DEPT_ID);



ALTER TABLE STUDENTS
ADD PHONE VARCHAR2(20);

ALTER TABLE STUDENTS
ADD STATUS VARCHAR2(10) DEFAULT 'ACTIVE';


ALTER TABLE STUDENTS
MODIFY PHONE VARCHAR2(30);


ALTER TABLE STUDENTS
DROP COLUMN STATUS;


ALTER TABLE STUDENTS
SET UNUSED (PHONE);


ALTER TABLE STUDENTS
DROP UNUSED COLUMNS;



CREATE TABLE STUDENTS_ARCHIVE
AS SELECT * FROM STUDENTS WHERE 1=0;



RENAME STUDENTS_ARCHIVE TO STUDENTS_OLD;



ALTER TABLE STUDENTS
ADD CONSTRAINT CHK_FEES CHECK (FEES >= 0);



ALTER TABLE STUDENTS
DISABLE CONSTRAINT CHK_FEES;


ALTER TABLE STUDENTS
ENABLE CONSTRAINT CHK_FEES;



ALTER TABLE STUDENTS
DROP CONSTRAINT UQ_EMAIL;



INSERT INTO DEPARTMENTS VALUES (10,'IT','PRETORIA');
INSERT INTO DEPARTMENTS VALUES (20,'BUSINESS','JOHANNESBURG');
INSERT INTO DEPARTMENTS VALUES (30,'COMPUTER SCIENCE','CAPE TOWN');

INSERT INTO STUDENTS VALUES (1,'John','Miller','john@email.com',SYSDATE,1500,10);
INSERT INTO STUDENTS VALUES (2,'Sarah','Smith','sarah@email.com',SYSDATE,2000,20);
INSERT INTO STUDENTS VALUES (3,'Mike','Brown','mike@email.com',SYSDATE,1200,10);
INSERT INTO STUDENTS VALUES (4,'Lisa','Moore','lisa@email.com',SYSDATE,3000,30);
INSERT INTO STUDENTS VALUES (5,'David','Martin','david@email.com',SYSDATE,800,20);



UPDATE STUDENTS
SET FEES = FEES * 1.10;



UPDATE STUDENTS
SET DEPT_ID =
(
SELECT DEPT_ID
FROM DEPARTMENTS
WHERE DEPT_NAME = 'COMPUTER SCIENCE'
)
WHERE DEPT_ID =
(
SELECT DEPT_ID
FROM DEPARTMENTS
WHERE DEPT_NAME = 'IT'
);



SELECT
FIRST_NAME LAST_NAME AS FULL_NAME,
DEPT_NAME,
ENROLL_DATE
FROM STUDENTS
JOIN DEPARTMENTS
ON STUDENTS.DEPT_ID = DEPARTMENTS.DEPT_ID;

SELECT *
FROM STUDENTS
WHERE FEES > 1000;

SELECT *
FROM STUDENTS
ORDER BY LAST_NAME;

SELECT FIRST_NAME, LAST_NAME, DEPT_NAME
FROM STUDENTS
INNER JOIN DEPARTMENTS
ON STUDENTS.DEPT_ID = DEPARTMENTS.DEPT_ID;

SELECT DEPT_NAME, COUNT * AS STUDENT_COUNT
FROM STUDENTS
JOIN DEPARTMENTS
ON STUDENTS.DEPT_ID = DEPARTMENTS.DEPT_ID
GROUP BY DEPT_NAME;

SELECT
SUM(FEES) AS TOTAL_FEES,
AVG(FEES) AS AVG_FEES,
MAX(FEES) AS MAX_FEES,
MIN(FEES) AS MIN_FEES
FROM STUDENTS;

SELECT *
FROM STUDENTS
WHERE LAST_NAME LIKE 'M%';

SELECT *
FROM STUDENTS
WHERE ENROLL_DATE BETWEEN
TO_DATE('2024-01-01','YYYY-MM-DD')
AND TO_DATE('2025-12-31','YYYY-MM-DD');

SELECT *
FROM STUDENTS
WHERE DEPT_ID IN (10,20,30);

SELECT DISTINCT DEPT_ID
FROM STUDENTS;



SELECT *
FROM STUDENTS
WHERE FEES >
(
SELECT AVG(FEES)
FROM STUDENTS
);

SELECT *
FROM DEPARTMENTS D
WHERE NOT EXISTS
(
SELECT *
FROM STUDENTS S
WHERE S.DEPT_ID = D.DEPT_ID
);

SELECT DEPT_NAME
FROM DEPARTMENTS
UNION
SELECT LAST_NAME
FROM STUDENTS;

SELECT
FIRST_NAME,
LAST_NAME,
FEES,
CASE
WHEN FEES > 5000 THEN 'HIGH'
WHEN FEES BETWEEN 2000 AND 5000 THEN 'MEDIUM'
ELSE 'LOW'
END AS FEE_CATEGORY
FROM STUDENTS;

SELECT DEPT_ID, COUNT(*) TOTAL
FROM STUDENTS
GROUP BY DEPT_ID
HAVING COUNT(*) > 3;



CREATE SEQUENCE SEQ_STUDENTS
START WITH 1000
INCREMENT BY 1;



CREATE INDEX IDX_LASTNAME
ON STUDENTS(LAST_NAME);



CREATE VIEW VW_STUDENT_DETAILS AS
SELECT
FIRST_NAME LAST_NAME AS FULL_NAME,
DEPT_NAME,
FEES
FROM STUDENTS
JOIN DEPARTMENTS
ON STUDENTS.DEPT_ID = DEPARTMENTS.DEPT_ID;


SELECT *
FROM
(
SELECT FIRST_NAME, LAST_NAME, FEES
FROM STUDENTS
ORDER BY FEES DESC
)
WHERE ROWNUM <= 3;



DROP VIEW VW_STUDENT_DETAILS;