CREATE TABLE STUDENTS (
    STUDENT_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(30),
    LAST_NAME VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(60) UNIQUE,
    ENROLL_DATE DATE NOT NULL,
    FEES NUMBER(8,2) DEFAULT 0);

ALTER TABLE STUDENTS
ADD DEPT_ID NUMBER
CONSTRAINT FK_STUDENTS_DEPT
REFERENCES DEPARTMENTS(DEPT_ID);

ALTER TABLE STUDENTS
ADD (PHONE VARCHAR2(20),
    STATUS VARCHAR2(10) DEFAULT 'ACTIVE');
    
ALTER TABLE STUDENTS
MODIFY PHONE VARCHAR2(30);

ALTER TABLE STUDENTS
DROP COLUMN STATUS;

ALTER TABLE STUDENTS
SET UNUSED (PHONE);

ALTER TABLE STUDENTS
DROP UNUSED COLUMNS;

CREATE TABLE STUDENTS_ARCHIVE
AS
SELECT *
FROM STUDENTS
WHERE 1 = 0;

RENAME STUDENTS_ARCHIVE TO STUDENTS_OLD;

ALTER TABLE STUDENTS
ADD CONSTRAINT CHK_FEES
CHECK (FEES >= 0);

ALTER TABLE STUDENTS
ADD CONSTRAINT UQ_EMAIL
UNIQUE (EMAIL)
DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE STUDENTS
DISABLE CONSTRAINT CHK_FEES;

ALTER TABLE STUDENTS
ENABLE CONSTRAINT CHK_FEES;

ALTER TABLE STUDENTS
DROP CONSTRAINT UQ_EMAIL;

INSERT INTO DEPARTMENTS (DEPT_ID, DEPT_NAME, LOCATION) VALUES (1, 'IT', 'Cape Town');
INSERT INTO DEPARTMENTS (DEPT_ID, DEPT_NAME, LOCATION) VALUES (2, 'HR', 'Johannesburg');
INSERT INTO DEPARTMENTS (DEPT_ID, DEPT_NAME, LOCATION) VALUES (3, 'FINANCE', 'Durban');

INSERT INTO STUDENTS (STUDENT_ID, FIRST_NAME, LAST_NAME, EMAIL, ENROLL_DATE, FEES, DEPT_ID)
VALUES (1, 'John', 'Smith', 'john@uni.com', SYSDATE, 1000, 1);
INSERT INTO STUDENTS (STUDENT_ID, FIRST_NAME, LAST_NAME, EMAIL, ENROLL_DATE, FEES, DEPT_ID)
VALUES (2, 'Sarah', 'Lee', 'sarah@uni.com', SYSDATE, 1200, 2);
INSERT INTO STUDENTS (STUDENT_ID, FIRST_NAME, LAST_NAME, EMAIL, ENROLL_DATE, FEES, DEPT_ID)
VALUES (3, 'Mike', 'Brown', 'mike@uni.com', SYSDATE, 900, 1);
INSERT INTO STUDENTS (STUDENT_ID, FIRST_NAME, LAST_NAME, EMAIL, ENROLL_DATE, FEES, DEPT_ID)
VALUES (4, 'Anna', 'White', 'anna@uni.com', SYSDATE, 1100, 3);
INSERT INTO STUDENTS (STUDENT_ID, FIRST_NAME, LAST_NAME, EMAIL, ENROLL_DATE, FEES, DEPT_ID)
VALUES (5, 'David', 'Green', 'david@uni.com', SYSDATE, 1300, 2);

UPDATE STUDENTS
SET FEES = FEES * 1.10;

DELETE FROM STUDENTS
WHERE STATUS = 'INACTIVE';

UPDATE STUDENTS
SET DEPT_ID = (
    SELECT DEPT_ID
    FROM DEPARTMENTS
    WHERE DEPT_NAME = 'COMPUTER SCIENCE'
)
WHERE DEPT_ID = (
    SELECT DEPT_ID
    FROM DEPARTMENTS
    WHERE DEPT_NAME = 'IT'
);

SELECT FIRST_NAME || ' ' || LAST_NAME AS FULL_NAME,
       D.DEPT_NAME,
       ENROLL_DATE
FROM STUDENTS S
LEFT JOIN DEPARTMENTS D ON S.DEPT_ID = D.DEPT_ID;

SELECT *
FROM STUDENTS
WHERE FEES > 1000;

SELECT *
FROM STUDENTS
ORDER BY LAST_NAME ASC;

SELECT S.STUDENT_ID, S.FIRST_NAME, S.LAST_NAME, D.DEPT_NAME
FROM STUDENTS S
INNER JOIN DEPARTMENTS D
ON S.DEPT_ID = D.DEPT_ID;


SELECT D.DEPT_NAME, COUNT(*) AS NUM_STUDENTS
FROM STUDENTS S
INNER JOIN DEPARTMENTS D
ON S.DEPT_ID = D.DEPT_ID
GROUP BY D.DEPT_NAME;

SELECT SUM(FEES) AS TOTAL_FEES,
       AVG(FEES) AS AVG_FEES,
       MAX(FEES) AS HIGHEST_FEES,
       MIN(FEES) AS LOWEST_FEES
FROM STUDENTS;

SELECT *
FROM STUDENTS
WHERE LAST_NAME LIKE 'M%';

SELECT *
FROM STUDENTS
WHERE ENROLL_DATE BETWEEN TO_DATE('2026-01-01','YYYY-MM-DD')
                      AND TO_DATE('2026-03-01','YYYY-MM-DD');

SELECT *
FROM STUDENTS
WHERE DEPT_ID IN (10, 20, 30);


SELECT DISTINCT D.DEPT_NAME
FROM STUDENTS S
INNER JOIN DEPARTMENTS D
ON S.DEPT_ID = D.DEPT_ID;

SELECT *
FROM STUDENTS
WHERE FEES > (SELECT AVG(FEES) FROM STUDENTS);

SELECT *
FROM DEPARTMENTS D
WHERE NOT EXISTS (
    SELECT 1
    FROM STUDENTS S
    WHERE S.DEPT_ID = D.DEPT_ID
);

SELECT DEPT_NAME AS NAME
FROM DEPARTMENTS
UNION
SELECT LAST_NAME AS NAME
FROM STUDENTS;

SELECT FIRST_NAME, LAST_NAME, FEES,
       CASE 
           WHEN FEES > 5000 THEN 'HIGH'
           WHEN FEES BETWEEN 2000 AND 5000 THEN 'MEDIUM'
           ELSE 'LOW'
       END AS FEE_CATEGORY
FROM STUDENTS;

SELECT D.DEPT_NAME, COUNT(*) AS NUM_STUDENTS
FROM STUDENTS S
INNER JOIN DEPARTMENTS D ON S.DEPT_ID = D.DEPT_ID
GROUP BY D.DEPT_NAME
HAVING COUNT(*) > 3;

CREATE SEQUENCE SEQ_STUDENTS
START WITH 1000
INCREMENT BY 1;

CREATE INDEX IDX_STUDENTS_LASTNAME
ON STUDENTS(LAST_NAME);

CREATE VIEW VW_STUDENT_DETAILS AS
SELECT S.FIRST_NAME || ' ' || S.LAST_NAME AS FULL_NAME,
       D.DEPT_NAME,
       S.FEES
FROM STUDENTS S
LEFT JOIN DEPARTMENTS D ON S.DEPT_ID = D.DEPT_ID;

SELECT *
FROM (
    SELECT S.FIRST_NAME || ' ' || S.LAST_NAME AS FULL_NAME, S.FEES
    FROM STUDENTS S
    ORDER BY S.FEES DESC
) 
WHERE ROWNUM <= 3;

DROP VIEW VW_STUDENT_DETAILS;

CREATE TABLE DEPARTMENTS (
    DEPT_ID NUMBER PRIMARY KEY,
    DEPT_NAME VARCHAR2(50) UNIQUE NOT NULL,
    LOCATION VARCHAR2(50));