--Section 1 - DDL(CREATE/ALTER/DROP)--
---Exercise 1 - Create a Table---

CREATE TABLE STUDENTS (
    STUDENT_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(30),
    LAST_NAME VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(60) UNIQUE,
    ENROLL_DATE DATE NOT NULL,
    FEES NUMBER(8,2) DEFAULT 0
);

--Exercise 2 - Create DEPARTMENTS Table--

CREATE TABLE DEPARTMENTS (
    DEPT_ID NUMBER PRIMARY KEY,
    DEPT_NAME VARCHAR2(50) UNIQUE NOT NULL,
    LOCATION VARCHAR2(50)
);

-- Exercise 3 - Foreign Key--

ALTER TABLE STUDENTS
ADD DEPT_ID NUMBER;

ALTER TABLE STUDENTS
ADD CONSTRAINT FK_DEPT
FOREIGN KEY (DEPT_ID)
REFERENCES DEPARTMENTS(DEPT_ID);

-- Exercise 4 - Add Columns--

ALTER TABLE STUDENTS
ADD (
    PHONE VARCHAR2(20),
    STATUS VARCHAR2(10) DEFAULT 'ACTIVE'
);

-- Exercise 5 - Modify Column--

ALTER TABLE STUDENTS
MODIFY PHONE VARCHAR2(30);

-- Exercise 6 - Drop Column --

ALTER TABLE STUDENTS
DROP COLUMN STATUS;

-- Exercise 7 - SET UNUSED --

ALTER TABLE STUDENTS
SET UNUSED (PHONE);

-- Exercise 8 - Drop All UNUSED Columns --

ALTER TABLE STUDENTS
DROP UNUSED COLUMNS;

-- Exercise 9 - Create a COPY of a Table --

CREATE TABLE STUDENTS_ARCHIVE
AS SELECT * FROM STUDENTS WHERE 1=0;

-- Exercise 10 - Rename Table --

RENAME STUDENTS_ARCHIVE TO STUDENTS_OLD;

-- SECTION 2 - CONSTRAINTS --
-- Exercise 11 - Add a CHECK constraint --

ALTER TABLE STUDENTS
ADD CONSTRAINT CHK_FEES
CHECK (FEES >= 0);

-- Exercise 12 - Add DEFERRABLE Constraint --

SELECT constraint_name
FROM user_constraints
WHERE table_name = 'STUDENTS';

ALTER TABLE STUDENTS
DROP CONSTRAINT SYS_C007003;

ALTER TABLE STUDENTS
ADD CONSTRAINT EMAIL_UNIQUE
UNIQUE (EMAIL)
DEFERRABLE INITIALLY DEFERRED;

-- Exercise 13 - Disable Constraint--

ALTER TABLE STUDENTS
DISABLE CONSTRAINT CHK_FEES;

-- Exercise 14 - Enable Constraint--

ALTER TABLE STUDENTS
ENABLE CONSTRAINT CHK_FEES;

-- Exercise 15 - Drop Constraint--

ALTER TABLE STUDENTS
DROP CONSTRAINT EMAIL_UNIQUE;

---SECTION 3 - DML(INSERT/UPDATE/DELETE)
-- Exercise 16 - INSERT departments--

INSERT INTO DEPARTMENTS VALUES (10,'IT','Building A');
INSERT INTO DEPARTMENTS VALUES (20,'HR','Building B');
INSERT INTO DEPARTMENTS VALUES (30,'FINANCE','Building C');

-- Exercise 17 - Insert Students--

INSERT INTO STUDENTS VALUES (1,'John','Smith','john@email.com',SYSDATE,1200,10);
INSERT INTO STUDENTS VALUES (2,'Mary','Brown','mary@email.com',SYSDATE,1500,20);
INSERT INTO STUDENTS VALUES (3,'David','Miller','david@email.com',SYSDATE,2000,10);
INSERT INTO STUDENTS VALUES (4,'Sarah','Moore','sarah@email.com',SYSDATE,900,30);
INSERT INTO STUDENTS VALUES (5,'James','Martin','james@email.com',SYSDATE,3000,10);

-- Exercise 18 - Increase Fees by 10%--

UPDATE STUDENTS
SET FEES = FEES * 1.10;

-- Exercise 19 - DELETE inactive students--

ALTER TABLE STUDENTS
ADD STATUS VARCHAR2(10) DEFAULT 'ACTIVE';

DELETE FROM STUDENTS
WHERE STATUS = 'INACTIVE';

-- Exercise 20 - Conditional Update--

UPDATE STUDENTS
SET DEPT_ID =
(
SELECT DEPT_ID FROM DEPARTMENTS
WHERE DEPT_NAME = 'COMPUTER SCIENCE'
)
WHERE DEPT_ID =
(
SELECT DEPT_ID FROM DEPARTMENTS
WHERE DEPT_NAME = 'IT'
);

---SECTION 4 - SELECT queries---
-- Exercise 21 - Basic SELECT

SELECT FIRST_NAME || ' ' || LAST_NAME AS FULL_NAME,
       DEPT_NAME,
       ENROLL_DATE
FROM STUDENTS S
JOIN DEPARTMENTS D
ON S.DEPT_ID = D.DEPT_ID;

--Exercise 22 - Filtering--

SELECT * FROM STUDENTS
WHERE FEES > 1000;

-- Exercise 23 - Sorting--

SELECT * FROM STUDENTS
ORDER BY LAST_NAME;

-- Exercise 24 - INNER JOIN--

SELECT S.FIRST_NAME,
       S.LAST_NAME,
       D.DEPT_NAME
FROM STUDENTS S
INNER JOIN DEPARTMENTS D
ON S.DEPT_ID = D.DEPT_ID;

-- Exercise 25 - GROUP by--

SELECT D.DEPT_NAME,
       COUNT(*) AS TOTAL_STUDENTS
FROM STUDENTS S
JOIN DEPARTMENTS D
ON S.DEPT_ID = D.DEPT_ID
GROUP BY D.DEPT_NAME;

-- Exercise 26 - Aggregate Functions--

SELECT
SUM(FEES) AS TOTAL_FEES,
AVG(FEES) AS AVERAGE_FEES,
MAX(FEES) AS HIGHEST_FEES,
MIN(FEES) AS LOWEST_FEES
FROM STUDENTS;

-- Exercise 27 - LIKE --

SELECT *
FROM STUDENTS
WHERE LAST_NAME LIKE 'M%';

-- Exercise 28 - BETWEEN --

SELECT *
FROM STUDENTS
WHERE ENROLL_DATE BETWEEN
TO_DATE('2024-01-01','YYYY-MM-DD')
AND
TO_DATE('2024-12-31','YYYY-MM-DD');

--Exercise 29 - IN--

SELECT *
FROM STUDENTS
WHERE DEPT_ID IN (10,20,30);

--Exercise 30 - DISTINCT--

SELECT DISTINCT DEPT_ID
FROM STUDENTS;

---SECTION 5 - ADVANCED SQL--
-- Exercise 31 - Subquery--

SELECT *
FROM STUDENTS
WHERE FEES >
(
SELECT AVG(FEES)
FROM STUDENTS
);

-- Exercise 32 - EXITS--

SELECT *
FROM DEPARTMENTS D
WHERE NOT EXISTS
(
SELECT *
FROM STUDENTS S
WHERE S.DEPT_ID = D.DEPT_ID
);

-- Exercise 33 - UNION--

SELECT DEPT_NAME FROM DEPARTMENTS
UNION
SELECT LAST_NAME FROM STUDENTS;

-- Exercise 34 - CASE Expression--

SELECT FIRST_NAME,
FEES,
CASE
WHEN FEES > 5000 THEN 'HIGH'
WHEN FEES BETWEEN 2000 AND 5000 THEN 'MEDIUM'
ELSE 'LOW'
END AS FEE_CATEGORY
FROM STUDENTS;

-- Exercise 35 - HAVING--

SELECT DEPT_ID,
COUNT(*) AS TOTAL_STUDENTS
FROM STUDENTS
GROUP BY DEPT_ID
HAVING COUNT(*) > 3;

--- SECTION 6 - INDEXES, SEQUENCES, VIEWS---
-- Exercise 36 - Create a Sequence--

CREATE SEQUENCE SEQ_STUDENTS
START WITH 1000
INCREMENT BY 1;

-- Exercise 37 - Create Index--

CREATE INDEX IDX_STUDENT_LASTNAME
ON STUDENTS(LAST_NAME);

-- Exercise 38 - Create a VIEW--

CREATE VIEW VW_STUDENT_DETAILS AS
SELECT
S.FIRST_NAME || ' ' || S.LAST_NAME AS FULL_NAME,
D.DEPT_NAME,
S.FEES
FROM STUDENTS S
JOIN DEPARTMENTS D
ON S.DEPT_ID = D.DEPT_ID;

--Exercise 39 - Inline View--

SELECT *
FROM
(
SELECT FIRST_NAME, LAST_NAME, FEES
FROM STUDENTS
ORDER BY FEES DESC
)
WHERE ROWNUM <= 3;

--Exercise 40 - DROP a VIEW--

DROP VIEW VW_STUDENT_DETAILS;