CREATE TABLE STUDENTS (
    STUDENT_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(30),
    LAST_NAME VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(60) UNIQUE,
    ENROLL_DATE DATE NOT NULL,
    FEES NUMBER(8,2) DEFAULT 0
);

CREATE TABLE DEPARTMENTS (
    DEPT_ID NUMBER PRIMARY KEY,
    DEPT_NAME VARCHAR2(50) UNIQUE NOT NULL,
    LOCATION VARCHAR2(50)
);

ALTER TABLE STUDENTS
ADD DEPT_ID NUMBER;

ALTER TABLE STUDENTS
ADD CONSTRAINT FK_STUDENTS_DEPT
FOREIGN KEY (DEPT_ID)
REFERENCES DEPARTMENTS(DEPT_ID);

ALTER TABLE STUDENTS
ADD (
    PHONE VARCHAR2(20),
    STATUS VARCHAR2(10) DEFAULT 'ACTIVE'
);

ALTER TABLE STUDENTS
MODIFY PHONE VARCHAR2(30);

ALTER TABLE STUDENTS
DROP COLUMN STATUS;

ALTER TABLE STUDENTS
SET UNUSED (PHONE);

CREATE TABLE STUDENTS_ARCHIVE
AS
SELECT *
FROM STUDENTS
WHERE 1 = 0;

RENAME STUDENTS_ARCHIVE TO STUDENTS_OLD;

ALTER TABLE STUDENTS
ADD CONSTRAINT chk_fees
CHECK (FEES >= 0);

ALTER TABLE STUDENTS
ADD CONSTRAINT uq_email
UNIQUE (EMAIL)
DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE STUDENTS
DISABLE CONSTRAINT chk_fees;

ALTER TABLE STUDENTS
DISABLE CONSTRAINT chk_fees;

ALTER TABLE STUDENTS
DROP CONSTRAINT uq_email;

INSERT INTO DEPARTMENTS VALUES (10, 'IT', 'BLOCK A');
INSERT INTO DEPARTMENTS VALUES (20, 'BUSINESS', 'BLOCK B');
INSERT INTO DEPARTMENTS VALUES (30, 'ACCOUNTING', 'BLOCK C');

INSERT INTO STUDENTS VALUES (1,'John','Miller','john@mail.com',SYSDATE,1200,10);
INSERT INTO STUDENTS VALUES (2,'Sarah','Brown','sarah@mail.com',SYSDATE,2500,20);
INSERT INTO STUDENTS VALUES (3,'David','Moore','david@mail.com',SYSDATE,3000,10);
INSERT INTO STUDENTS VALUES (4,'Lisa','Martin','lisa@mail.com',SYSDATE,800,30);
INSERT INTO STUDENTS VALUES (5,'James','Mason','james@mail.com',SYSDATE,5000,20);

UPDATE STUDENTS
SET FEES = FEES * 1.10;

DELETE FROM STUDENTS
WHERE STATUS = 'INACTIVE';

UPDATE STUDENTS
SET DEPT_ID =
(
SELECT DEPT_ID
FROM DEPARTMENTS
WHERE DEPT_NAME = 'COMPUTER SCIENCE'
)
WHERE DEPT_ID =
(
SELECT DEPT_ID
FROM DEPARTMENTS
WHERE DEPT_NAME = 'IT'
);

SELECT
FIRST_NAME || ' ' || LAST_NAME AS FULL_NAME,
DEPT_NAME,
ENROLL_DATE
FROM STUDENTS S
JOIN DEPARTMENTS D
ON S.DEPT_ID = D.DEPT_ID;

SELECT *
FROM STUDENTS
WHERE FEES > 1000;
-
SELECT
S.FIRST_NAME,
S.LAST_NAME,
D.DEPT_NAME
FROM STUDENTS S
INNER JOIN DEPARTMENTS D
ON S.DEPT_ID = D.DEPT_ID;

SELECT
S.FIRST_NAME,
S.LAST_NAME,
D.DEPT_NAME
FROM STUDENTS S
INNER JOIN DEPARTMENTS D
ON S.DEPT_ID = D.DEPT_ID;

SELECT
D.DEPT_NAME,
COUNT(*) AS STUDENT_COUNT
FROM STUDENTS S
JOIN DEPARTMENTS D
ON S.DEPT_ID = D.DEPT_ID
GROUP BY D.DEPT_NAME;

SELECT
SUM(FEES) AS TOTAL_FEES,
AVG(FEES) AS AVG_FEES,
MAX(FEES) AS HIGHEST_FEES,
MIN(FEES) AS LOWEST_FEES
FROM STUDENTS;

SELECT *
FROM STUDENTS
WHERE LAST_NAME LIKE 'M%';

SELECT *
FROM STUDENTS
WHERE ENROLL_DATE BETWEEN
TO_DATE('01-JAN-2023','DD-MON-YYYY')
AND
TO_DATE('31-DEC-2023','DD-MON-YYYY');

SELECT *
FROM STUDENTS
WHERE DEPT_ID IN (10,20,30);

SELECT DISTINCT DEPT_ID
FROM STUDENTS;

SELECT *
FROM STUDENTS
WHERE FEES >
(
SELECT AVG(FEES)
FROM STUDENTS
);

SELECT *
FROM DEPARTMENTS D
WHERE NOT EXISTS
(
SELECT *
FROM STUDENTS S
WHERE S.DEPT_ID = D.DEPT_ID
);

SELECT DEPT_NAME
FROM DEPARTMENTS

UNION

SELECT LAST_NAME
FROM STUDENTS;

SELECT
FIRST_NAME,
LAST_NAME,
FEES,
CASE
WHEN FEES > 5000 THEN 'HIGH'
WHEN FEES BETWEEN 2000 AND 5000 THEN 'MEDIUM'
ELSE 'LOW'
END AS FEE_LEVEL
FROM STUDENTS;

SELECT
DEPT_ID,
COUNT(*) AS TOTAL_STUDENTS
FROM STUDENTS
GROUP BY DEPT_ID
HAVING COUNT(*) > 3;

CREATE SEQUENCE SEQ_STUDENTS
START WITH 1000
INCREMENT BY 1;

CREATE INDEX IDX_STUDENT_LASTNAME
ON STUDENTS(LAST_NAME);
-------------------
CREATE VIEW VW_STUDENT_DETAILS AS
SELECT
S.FIRST_NAME || ' ' || S.LAST_NAME AS FULL_NAME,
D.DEPT_NAME,
S.FEES
FROM STUDENTS S
JOIN DEPARTMENTS D
ON S.DEPT_ID = D.DEPT_ID;

SELECT *
FROM
(
SELECT *
FROM STUDENTS
ORDER BY FEES DESC
)
WHERE ROWNUM <= 3;

SELECT *
FROM
(
SELECT *
FROM STUDENTS
ORDER BY FEES DESC
)
WHERE ROWNUM <= 3;